services:
  snippet-db:
    image: postgres:16-alpine
    container_name: snippet-db
    env_file: [.env]
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    volumes:
      - pg_data:/var/lib/postg-resql/data

  language-service:
    image: ghcr.io/ingenieria-de-sistemas-123/language-service:latest
    platform: linux/amd64
    container_name: language-service
    ports:
    - "8080:8080"
    environment:
    - SPRING_PROFILES_ACTIVE=docker

  snippet-service:
    build: .
    container_name: snippet-service
    depends_on:
      snippet-db:
        condition: service_healthy
      language-service:
        condition: service_started
    env_file: [.env]
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LANGUAGE_BASE_URL=http://language-service:8080

volumes:
  pg_data: